/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Board: typeof import('./components/Board.vue')['default']
    Btn: typeof import('./components/common/Btn.vue')['default']
    Card: typeof import('./components/Card.vue')['default']
    IFluentGlasses48Regular: typeof import('~icons/fluent/glasses48-regular')['default']
    IFluentGlassesOff48Regular: typeof import('~icons/fluent/glasses-off48-regular')['default']
    IMdiEyeOffOutline: typeof import('~icons/mdi/eye-off-outline')['default']
    IMdiEyeOutline: typeof import('~icons/mdi/eye-outline')['default']
    IMdiLogin: typeof import('~icons/mdi/login')['default']
    IMdiLogout: typeof import('~icons/mdi/logout')['default']
    IMdiRestart: typeof import('~icons/mdi/restart')['default']
    IMdiVote: typeof import('~icons/mdi/vote')['default']
    Layout: typeof import('./components/Layout.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    Modal: typeof import('./components/common/Modal.vue')['default']
    Mode: typeof import('./components/common/Mode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserList: typeof import('./components/UserList.vue')['default']
  }
}
