name: CI
on:
  push:
    branches:
      - main

concurrency: build

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 19, 20]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Test
        run: |
          pnpm install
          pnpm run test
          pnpm run build